# Generated by Django 4.1.5 on 2023-01-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_emaildetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="authorization",
            field=models.TextField(default=None, null=True),
        ),
    ]
