# Generated by Django 4.1.5 on 2023-01-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_website_authorization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downtime",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="downtime",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uptime",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uptime",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
