# Generated by Django 4.1.5 on 2023-01-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_alter_downtime_end_time_alter_downtime_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="authorization_type",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("BASIC AUTH", "Basic Auth"),
                    ("API KEY", "API Key"),
                    ("BEARER TOKEN", "Bearer Token"),
                    ("TOKEN", "Token"),
                ],
                default="NONE",
                max_length=50,
            ),
        ),
    ]
